#!/bin/sh

# Status bar module for disk space
# $1 should be drive mountpoint, otherwise assumed /.

location=/home
[ -d "$location" ] || exit

icon=" "

echo "$icon $(df -h "$location" | awk 'NR==2 {printf "%s %s\n", $3, $5}')"
